baseURL = 'https://helium24.net/'
locale = 'en-us'
title = 'Helium24.net'
enableRobotsTXT = true

[taxonomies]
# tag = ""
# category = ""

[[menus.main]]
name = "Projects"
pageRef = "/projects"
weight = 20

[[menus.main]]
name = "Simulation"
pageRef = "/projects/simulation"
weight = 30